/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started with RxDB',
      collapsed: false,
      items: [
        'quickstart',
        'install',
        'dev-mode',
        'tutorials/typescript',
      ]
    },
    {
      type: 'category',
      label: 'Core Entities',
      collapsed: false,
      items: [
        'rx-database',
        'rx-schema',
        'rx-collection',
        'rx-document',
        'rx-query'
      ]
    },
    {
      type: 'category',
      label: '💾 Storages',
      items: [
        'rx-storage',
        'rx-storage-indexeddb',
        'rx-storage-sqlite',
        'rx-storage-memory',
        'rx-storage-dexie',
        'rx-storage-opfs',
        'rx-storage-filesystem-node',
        'rx-storage-mongodb',
        'rx-storage-denokv',
        'rx-storage-foundationdb'
      ],
    },
    {
      type: 'category',
      label: 'Storage Wrappers',
      items: [
        'schema-validation',
        'encryption',
        'key-compression',
        'logger',
        'rx-storage-remote',
        'rx-storage-worker',
        'rx-storage-shared-worker',
        'rx-storage-memory-mapped',
        'rx-storage-memory-synced',
        'rx-storage-sharding',
        'rx-storage-localstorage-meta-optimizer',
        'electron'
      ],
    },
    {
      type: 'category',
      label: '🔄 Replication',
      items: [
        'replication',
        'replication-http',
        'replication-server',
        'replication-graphql',
        'replication-websocket',
        'replication-couchdb',
        'replication-webrtc',
        'replication-firestore',
        'replication-nats'
      ],
    },
    {
      type: 'category',
      label: 'Server',
      items: [
        'rx-server',
        'rx-server-scaling',
      ],
    },
    {
      type: 'category',
      label: 'How RxDB works',
      items: [
        'transactions-conflicts-revisions',
        'query-cache',
        'plugins',
        'errors',
      ],
    }, {
      type: 'category',
      label: 'Advanced Features',
      items: [
        {
          type: 'category',
          label: 'Migration',
          items: [
            'migration-schema',
            'migration-storage'
          ],
        },
        'rx-attachment',
        'rx-pipeline',
        'reactivity',
        'rx-state',
        'rx-local-document',
        'cleanup',
        'backup',
        'leader-election',
        'middleware',
        'crdt',
        'population',
        'orm',
        'fulltext-search',
        'query-optimizer',
        'third-party-plugins',
      ],
    },
    {
      type: 'category',
      label: 'Performance',
      items: [
        'rx-storage-performance',
        'nosql-performance-tips',
        'slow-indexeddb',
        'articles/localstorage-indexeddb-cookies-opfs-sqlite-wasm',
      ],
    },
    {
      type: 'category',
      label: '🆕 Releases',
      items: [
        'releases/16.0.0',
        'releases/15.0.0',
        'releases/14.0.0',
        'releases/13.0.0',
        'releases/12.0.0',
        'releases/11.0.0',
        'releases/10.0.0',
        'releases/9.0.0',
        'releases/8.0.0',
      ],
    },
    {
      type: 'category',
      label: 'Articles',
      items: [
        'offline-first',
        'downsides-of-offline-first',
        'why-nosql',
        'nodejs-database',
        'alternatives',
        'react-native-database',
        'articles/javascript-vector-database',
        'articles/angular-database',
        'articles/browser-database',
        'articles/browser-storage',
        'articles/data-base',
        'articles/embedded-database',
        'articles/flutter-database',
        'articles/frontend-database',
        'articles/in-memory-nosql-database',
        'articles/ionic-database',
        'articles/json-database',
        'articles/websockets-sse-polling-webrtc-webtransport',
        'articles/localstorage',
        'articles/mobile-database',
        'articles/progressive-web-app-database',
        'articles/react-database',
        'articles/realtime-database',
        'articles/angular-indexeddb',
        'articles/react-indexeddb',
        'capacitor-database',
        'electron-database',
        'articles/optimistic-ui',
        'articles/local-database',
      ],
    },
    'contribute',
    {
      type: 'category',
      label: 'Contact',
      items: [
        {
          type: 'link',
          label: 'Consulting',
          href: '/consulting'
        },
        {
          type: 'link',
          label: 'Discord',
          href: '/chat',
          customProps: {
            /**
             * Does not work! Missing feature in docusaurus.
             * @link https://docusaurus.canny.io/feature-requests/p/support-target-for-sidebar-links
             */
            target: '_blank'
          }
        },
        {
          type: 'link',
          label: 'LinkedIn',
          href: 'https://www.linkedin.com/company/rxdb/'
        },
      ],
    },

  ],
};

export default sidebars;
